modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="global_os_mod"
version="1.0.0"
displayName="global_os_mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="теомир, MCreator"

[[dependencies.global_os_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




